### ISSUE TITLE
idk this eror

### ISSUE THREAD

**Issue by laynz28** [ardha27/AICoverGen-NoUI-Colab#6]
<All keys matched successfully>
Traceback (most recent call last):
  File "/content/AICoverGen/AICoverGen/src/main.py", line 291, in song_cover_pipeline
    voice_change(voice_model, main_vocals_dereverb_path, ai_vocals_path, pitch_change, f0_method, index_rate, filter_radius, rms_mix_rate, protect, crepe_hop_length, is_webui)
  File "/content/AICoverGen/AICoverGen/src/main.py", line 201, in voice_change
    rvc_infer(rvc_index_path, index_rate, vocals_path, output_path, pitch_change, f0_method, cpt, version, net_g, filter_radius, tgt_sr, rms_mix_rate, protect, crepe_hop_length, vc, hubert_model)
  File "/content/AICoverGen/AICoverGen/src/rvc.py", line 150, in rvc_infer
    audio_opt = vc.pipeline(hubert_model, net_g, 0, audio, input_path, times, pitch_change, f0_method, index_path, index_rate, if_f0, filter_radius, tgt_sr, 0, rms_mix_rate, version, protect, crepe_hop_length)
  File "/content/AICoverGen/AICoverGen/src/vc_infer_pipeline.py", line 571, in pipeline
    self.vc(
  File "/content/AICoverGen/AICoverGen/src/vc_infer_pipeline.py", line 424, in vc
    npy = np.sum(big_npy[ix] * np.expand_dims(weight, axis=2), axis=1)
IndexError: index -1 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/AICoverGen/AICoverGen/src/main.py", line 346, in <module>
    cover_path = song_cover_pipeline(args.song_input, rvc_dirname, args.pitch_change, args.keep_files,
  File "/content/AICoverGen/AICoverGen/src/main.py", line 316, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "/content/AICoverGen/AICoverGen/src/main.py", line 85, in raise_exception
    raise Exception(error_msg)
Exception: index -1 is out of bounds for axis 0 with size 0

**Comment by Dashman23** [comment]
I'm having the same issue, i'm not sure why...

**Comment by ardha27** [comment]
There are limit on each parameter, if you go beyond, it will give error

**Comment by Dashman23** [comment]
What are the parameters? Is there a doc to read?

**Comment by ardha27** [comment]
Go to the original repo
